local meld = require('meld')


---@type {[string]:SignalID}
local sigmap = {
  ["0"]={ quality="normal", type="virtual", name='signal-0'},
  ["1"]={ quality="normal", type="virtual", name='signal-1'},
  ["2"]={ quality="normal", type="virtual", name='signal-2'},
  ["3"]={ quality="normal", type="virtual", name='signal-3'},
  ["4"]={ quality="normal", type="virtual", name='signal-4'},
  ["5"]={ quality="normal", type="virtual", name='signal-5'},
  ["6"]={ quality="normal", type="virtual", name='signal-6'},
  ["7"]={ quality="normal", type="virtual", name='signal-7'},
  ["8"]={ quality="normal", type="virtual", name='signal-8'},
  ["9"]={ quality="normal", type="virtual", name='signal-9'},

  ["a"]={ quality="normal", type="virtual", name='signal-A'},
  ["b"]={ quality="normal", type="virtual", name='signal-B'},
  ["c"]={ quality="normal", type="virtual", name='signal-C'},
  ["d"]={ quality="normal", type="virtual", name='signal-D'},
  ["e"]={ quality="normal", type="virtual", name='signal-E'},
  ["f"]={ quality="normal", type="virtual", name='signal-F'},
  ["g"]={ quality="normal", type="virtual", name='signal-G'},
  ["h"]={ quality="normal", type="virtual", name='signal-H'},
  ["i"]={ quality="normal", type="virtual", name='signal-I'},
  ["j"]={ quality="normal", type="virtual", name='signal-J'},
  ["k"]={ quality="normal", type="virtual", name='signal-K'},
  ["l"]={ quality="normal", type="virtual", name='signal-L'},
  ["m"]={ quality="normal", type="virtual", name='signal-M'},
  ["n"]={ quality="normal", type="virtual", name='signal-N'},
  ["o"]={ quality="normal", type="virtual", name='signal-O'},
  ["p"]={ quality="normal", type="virtual", name='signal-P'},
  ["q"]={ quality="normal", type="virtual", name='signal-Q'},
  ["r"]={ quality="normal", type="virtual", name='signal-R'},
  ["s"]={ quality="normal", type="virtual", name='signal-S'},
  ["t"]={ quality="normal", type="virtual", name='signal-T'},
  ["u"]={ quality="normal", type="virtual", name='signal-U'},
  ["v"]={ quality="normal", type="virtual", name='signal-V'},
  ["w"]={ quality="normal", type="virtual", name='signal-W'},
  ["x"]={ quality="normal", type="virtual", name='signal-X'},
  ["y"]={ quality="normal", type="virtual", name='signal-Y'},
  ["z"]={ quality="normal", type="virtual", name='signal-Z'},

  ["💀"]={ quality="normal", type="virtual", name="signal-skull" }, -- 1F480
  ["👻"]={ quality="normal", type="virtual", name="signal-ghost" }, -- 1F47B
  ["🛈"]={ quality="normal", type="virtual", name="signal-info" }, -- 1F6C8

  ["✓"]={ quality="normal", type="virtual", name="signal-check" },
  ["❌"]={ quality="normal", type="virtual", name="signal-deny" },
  ["·"]={ quality="normal", type="virtual", name="signal-dot" },
  ["$"]={ quality="normal", type="item", name="coin" },
  ["♥"]={ quality="normal", type="virtual", name="signal-heart" },
  ["⚠"]={ quality="normal", type="virtual", name="signal-alert" },
  ["⭐"]={ quality="normal", type="virtual", name="signal-star" },
  ["!"]={ quality="normal", type="virtual", name="signal-exclamation-mark" },
  ["\""]={ quality="normal", type="virtual", name="signal-quotation-mark" },
  ["#"]={ quality="normal", type="virtual", name="signal-number-sign" },
  ["%"]={ quality="normal", type="virtual", name="signal-percent" },
  ["&"]={ quality="normal", type="virtual", name="signal-ampersand" },
  ["'"]={ quality="normal", type="virtual", name="signal-apostrophe" },
  ["("]={ quality="normal", type="virtual", name="signal-left-parenthesis" },
  [")"]={ quality="normal", type="virtual", name="signal-right-parenthesis" },
  ["*"]={ quality="normal", type="virtual", name="signal-multiplication" },
  ["+"]={ quality="normal", type="virtual", name="signal-plus" },
  [","]={ quality="normal", type="virtual", name="signal-comma" },
  ["-"]={ quality="normal", type="virtual", name="signal-minus" },
  ["."]={ quality="normal", type="virtual", name="signal-letter-dot" },
  ["/"]={ quality="normal", type="virtual", name="signal-slash" },
  [":"]={ quality="normal", type="virtual", name="signal-colon" },
  ["<"]={ quality="normal", type="virtual", name="signal-less-than" },
  ["="]={ quality="normal", type="virtual", name="signal-equal" },
  [">"]={ quality="normal", type="virtual", name="signal-greater-than" },
  ["?"]={ quality="normal", type="virtual", name="signal-question-mark" },
  ["["]={ quality="normal", type="virtual", name="signal-left-square-bracket" },
  ["]"]={ quality="normal", type="virtual", name="signal-right-square-bracket" },
  ["^"]={ quality="normal", type="virtual", name="signal-circumflex-accent" },
  ["÷"]={ quality="normal", type="virtual", name="signal-division" },
  ["≤"]={ quality="normal", type="virtual", name="signal-less-than-or,-equal-to" },
  ["≠"]={ quality="normal", type="virtual", name="signal-not-equal" },
  ["≥"]={ quality="normal", type="virtual", name="signal-greater-than-or-equal-to" },
  ["│"]={ quality="normal", type="virtual", name="shape-vertical" },
  ["─"]={ quality="normal", type="virtual", name="shape-horizontal" },
  ["╭"]={ quality="normal", type="virtual", name="shape-curve" },
  ["╮"]={ quality="normal", type="virtual", name="shape-curve-2" },
  ["┌"]={ quality="normal", type="virtual", name="shape-corner" },
  ["┐"]={ quality="normal", type="virtual", name="shape-corner-2" },
  ["┬"]={ quality="normal", type="virtual", name="shape-t" },
  ["┤"]={ quality="normal", type="virtual", name="shape-t-2" },
  ["┼"]={ quality="normal", type="virtual", name="shape-cross" },
  ["╳"]={ quality="normal", type="virtual", name="shape-diagonal-cross" },
  ["╱"]={ quality="normal", type="virtual", name="shape-diagonal" },
  ["╲"]={ quality="normal", type="virtual", name="shape-diagonal-2" },
  ["╰"]={ quality="normal", type="virtual", name="shape-curve-3" },
  ["╯"]={ quality="normal", type="virtual", name="shape-curve-4" },
  ["└"]={ quality="normal", type="virtual", name="shape-corner-4" },
  ["┘"]={ quality="normal", type="virtual", name="shape-corner-3" },
  ["├"]={ quality="normal", type="virtual", name="shape-t-4" },
  ["┴"]={ quality="normal", type="virtual", name="shape-t-3" },
  ["◯"]={ quality="normal", type="virtual", name="shape-circle" },
  ["↑"]={ quality="normal", type="virtual", name="up-arrow" },
  ["↗"]={ quality="normal", type="virtual", name="up-right-arrow" },
  ["→"]={ quality="normal", type="virtual", name="right-arrow" },
  ["↘"]={ quality="normal", type="virtual", name="down-right-arrow" },
  ["↓"]={ quality="normal", type="virtual", name="down-arrow" },
  ["↙"]={ quality="normal", type="virtual", name="down-left-arrow" },
  ["←"]={ quality="normal", type="virtual", name="left-arrow" },
  ["↖"]={ quality="normal", type="virtual", name="up-left-arrow" },
  ["↔"]={ quality="normal", type="virtual", name="signal-left-right-arrow" },
  ["↕"]={ quality="normal", type="virtual", name="signal-up-down-arrow" },
  ["↩"]={ quality="normal", type="virtual", name="signal-clockwise-circle-arrow" },
  ["↪"]={ quality="normal", type="virtual", name="signal-anticlockwise-circle-arrow" },
}

if feature_flags["quality"] then
  meld.meld(sigmap, {
    
    ["A"]={ quality="uncommon", type="virtual", name='signal-A'},
    ["B"]={ quality="uncommon", type="virtual", name='signal-B'},
    ["C"]={ quality="uncommon", type="virtual", name='signal-C'},
    ["D"]={ quality="uncommon", type="virtual", name='signal-D'},
    ["E"]={ quality="uncommon", type="virtual", name='signal-E'},
    ["F"]={ quality="uncommon", type="virtual", name='signal-F'},
    ["G"]={ quality="uncommon", type="virtual", name='signal-G'},
    ["H"]={ quality="uncommon", type="virtual", name='signal-H'},
    ["I"]={ quality="uncommon", type="virtual", name='signal-I'},
    ["J"]={ quality="uncommon", type="virtual", name='signal-J'},
    ["K"]={ quality="uncommon", type="virtual", name='signal-K'},
    ["L"]={ quality="uncommon", type="virtual", name='signal-L'},
    ["M"]={ quality="uncommon", type="virtual", name='signal-M'},
    ["N"]={ quality="uncommon", type="virtual", name='signal-N'},
    ["O"]={ quality="uncommon", type="virtual", name='signal-O'},
    ["P"]={ quality="uncommon", type="virtual", name='signal-P'},
    ["Q"]={ quality="uncommon", type="virtual", name='signal-Q'},
    ["R"]={ quality="uncommon", type="virtual", name='signal-R'},
    ["S"]={ quality="uncommon", type="virtual", name='signal-S'},
    ["T"]={ quality="uncommon", type="virtual", name='signal-T'},
    ["U"]={ quality="uncommon", type="virtual", name='signal-U'},
    ["V"]={ quality="uncommon", type="virtual", name='signal-V'},
    ["W"]={ quality="uncommon", type="virtual", name='signal-W'},
    ["X"]={ quality="uncommon", type="virtual", name='signal-X'},
    ["Y"]={ quality="uncommon", type="virtual", name='signal-Y'},
    ["Z"]={ quality="uncommon", type="virtual", name='signal-Z'},
  })
end

data.extend{
  {
    type = "mod-data",
    name = "signalstrings-mapping",
    data_type = "signalstrings-mapping",
    data = sigmap,
  }
}